/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef down_parse_client_CONSTANTS_H
#define down_parse_client_CONSTANTS_H

#include "down_parse_client_types.h"



class down_parse_clientConstants {
 public:
  down_parse_clientConstants();

};

extern const down_parse_clientConstants g_down_parse_client_constants;



#endif
