/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "down_parse_client_constants.h"



const down_parse_clientConstants g_down_parse_client_constants;

down_parse_clientConstants::down_parse_clientConstants() {
}



