/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef wendao_CONSTANTS_H
#define wendao_CONSTANTS_H

#include "wendao_types.h"

namespace wendao {

class wendaoConstants {
 public:
  wendaoConstants();

  std::map<std::string, std::string>  MAPCONSTANT;
};

extern const wendaoConstants g_wendao_constants;

} // namespace

#endif
