/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef download_CONSTANTS_H
#define download_CONSTANTS_H

#include "download_types.h"



class downloadConstants {
 public:
  downloadConstants();

};

extern const downloadConstants g_download_constants;



#endif
