/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "wendao_constants.h"

namespace wendao {

const wendaoConstants g_wendao_constants;

wendaoConstants::wendaoConstants() {
  MAPCONSTANT.insert(std::make_pair("hello", "world"));
  MAPCONSTANT.insert(std::make_pair("goodnight", "moon"));

}

} // namespace

