/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "download_constants.h"



const downloadConstants g_download_constants;

downloadConstants::downloadConstants() {
}



