/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "parser_thrift/srpp_parser_constants.h"



const srpp_parserConstants g_srpp_parser_constants;

srpp_parserConstants::srpp_parserConstants() {
}



