/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef srpp_parser_CONSTANTS_H
#define srpp_parser_CONSTANTS_H

#include "srpp_parser_types.h"



class srpp_parserConstants {
 public:
  srpp_parserConstants();

};

extern const srpp_parserConstants g_srpp_parser_constants;



#endif
