/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "server/page_download_constants.h"

namespace page_download {

const page_downloadConstants g_page_download_constants;

page_downloadConstants::page_downloadConstants() {
}

} // namespace

