/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef page_download_CONSTANTS_H
#define page_download_CONSTANTS_H

#include "server/page_download_types.h"

namespace page_download {

class page_downloadConstants {
 public:
  page_downloadConstants();

};

extern const page_downloadConstants g_page_download_constants;

} // namespace

#endif
