/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dms_CONSTANTS_H
#define dms_CONSTANTS_H

#include "dms_types.h"



class dmsConstants {
 public:
  dmsConstants();

};

extern const dmsConstants g_dms_constants;



#endif
