/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dms_constants.h"



const dmsConstants g_dms_constants;

dmsConstants::dmsConstants() {
}



